export const styles = {
  app: {
    fontFamily: "'Segoe UI', Tahoma, 'Geeza Pro', Arial, sans-serif",
    background: "#EEF3F2",
    minHeight: "100vh",
    color: "#1B2B2A",
    overflowX: "hidden",
  },
  loadingScreen: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    background: "#EEF3F2",
  },
  spinner: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "3px solid #CFE0DE",
    borderTopColor: "#145C5C",
    animation: "spin 0.8s linear infinite",
  },
  header: {
    background: "linear-gradient(135deg, #145C5C 0%, #0E4747 100%)",
    padding: "14px 18px",
    color: "#F6F5F1",
  },
  headerTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  headerTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  headerLogo: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "rgba(255,255,255,0.14)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  h1: { fontSize: 16, margin: 0, fontWeight: 800, lineHeight: 1.25 },
  subtitle: { fontSize: 11, opacity: 0.82, marginTop: 2, maxWidth: 300 },
  authRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  roleTag: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 10.5,
    background: "rgba(255,255,255,0.14)",
    padding: "5px 10px",
    borderRadius: 999,
    fontWeight: 700,
    maxWidth: 220,
    minWidth: 0,
  },
  roleTagFixed: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0, whiteSpace: "nowrap" },
  roleTagEmail: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerIconBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "none",
    background: "rgba(255,255,255,0.14)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  kpiRow: { display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" },
  kpi: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 11px",
    borderRadius: 12,
    flex: "1 1 150px",
    minWidth: 0,
  },
  kpiIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: "rgba(255,255,255,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  kpiValue: { fontSize: 18, fontWeight: 800, lineHeight: 1.15 },
  kpiLabel: { fontSize: 10.5, marginTop: 2, opacity: 0.92 },
  // Button-reset so a KPI card rendered as a real <button> (see
  // components/Kpi.jsx) looks pixel-identical to the plain-div version —
  // hover/active/focus visuals live in global.css (.kpi-card-clickable).
  kpiClickable: {
    border: "none",
    fontFamily: "inherit",
    textAlign: "inherit",
    width: "100%",
    cursor: "pointer",
  },
  filterBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    background: "#EAF1F0",
    color: "#3A4E4C",
    fontSize: 12.5,
    fontWeight: 600,
    padding: "8px 14px",
    marginBottom: 12,
    borderRadius: 10,
  },
  filterBannerClear: {
    border: "none",
    background: "none",
    color: "#145C5C",
    fontWeight: 700,
    textDecoration: "underline",
    cursor: "pointer",
    fontSize: 12.5,
    padding: 0,
    fontFamily: "inherit",
  },
  tabs: {
    display: "flex",
    gap: 4,
    padding: "8px 12px 0",
    background: "#EEF3F2",
    borderBottom: "1px solid #D7E4E2",
    overflowX: "auto",
  },
  tabBtn: (active) => ({
    border: "none",
    background: "none",
    padding: "10px 12px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    color: active ? "#145C5C" : "#7C918F",
    borderBottom: active ? "2.5px solid #145C5C" : "2.5px solid transparent",
    whiteSpace: "nowrap",
  }),
  saveInfo: {
    background: "#EAF1F0",
    color: "#5B6E6D",
    fontSize: 12,
    padding: "6px 12px",
    textAlign: "center",
  },
  saveError: {
    background: "#FBE7E4",
    color: "#9A2E23",
    fontSize: 12.5,
    padding: "8px 12px",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  retryLink: {
    border: "none",
    background: "none",
    color: "#9A2E23",
    fontWeight: 700,
    textDecoration: "underline",
    cursor: "pointer",
    fontSize: 12.5,
    padding: 0,
  },
  body: {
    display: "flex",
    gap: 14,
    padding: "14px 12px 40px",
    alignItems: "flex-start",
    maxWidth: "100%",
  },
  sidebar: {
    width: 180,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    background: "#fff",
    borderRadius: 14,
    padding: 10,
    border: "1px solid #DCE8E6",
  },
  sideItemRow: { display: "flex", alignItems: "center", gap: 2 },
  sideItem: (active) => ({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    border: "none",
    background: active ? "#E7F3F1" : "transparent",
    color: active ? "#145C5C" : "#3A4E4C",
    fontWeight: active ? 700 : 500,
    padding: "9px 10px",
    borderRadius: 8,
    fontSize: 12.5,
    cursor: "pointer",
    textAlign: "right",
  }),
  editPencil: {
    border: "none",
    background: "none",
    color: "#B7C7C5",
    cursor: "pointer",
    padding: 4,
    flexShrink: 0,
  },
  // Category drag handle (admin-only) — deliberately a separate small
  // control from the category button itself, so pressing/dragging it can
  // never be confused with a normal category-select click.
  dragHandle: {
    border: "none",
    background: "none",
    color: "#B7C7C5",
    cursor: "grab",
    padding: 4,
    flexShrink: 0,
    display: "flex",
    touchAction: "none",
  },
  countBadge: { fontSize: 11, color: "#7C918F" },
  addCategoryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
    marginTop: 6,
    border: "1px dashed #B7C7C5",
    background: "none",
    color: "#5B6E6D",
    padding: "8px 10px",
    borderRadius: 8,
    fontSize: 12.5,
    cursor: "pointer",
    flexShrink: 0,
  },
  main: { flex: 1, minWidth: 0, width: "100%" },
  toolbar: {
    display: "flex",
    gap: 10,
    marginBottom: 12,
    alignItems: "center",
    flexWrap: "wrap",
  },
  sessionBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 10,
    padding: "9px 10px",
    marginBottom: 14,
    flexWrap: "wrap",
  },
  sessionLabel: { fontSize: 12, fontWeight: 700, color: "#3A4E4C" },
  sessionInput: {
    border: "1px solid #DCE8E6",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 12.5,
    fontFamily: "inherit",
    color: "#1B2B2A",
    background: "#fff",
  },
  sessionHint: { fontSize: 10.5, color: "#B7C7C5" },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 10,
    padding: "8px 12px",
    flex: 1,
    minWidth: 160,
  },
  searchInput: {
    border: "none",
    outline: "none",
    fontSize: 13.5,
    flex: 1,
    background: "transparent",
    color: "#1B2B2A",
    minWidth: 0,
  },
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#145C5C",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "9px 14px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  secondaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "#F1F6F5",
    color: "#145C5C",
    border: "1px solid #DCE8E6",
    borderRadius: 8,
    padding: "7px 10px",
    fontSize: 12.5,
    fontWeight: 700,
    cursor: "pointer",
    flex: 1,
    justifyContent: "center",
  },
  btnDisabled: { opacity: 0.4, cursor: "not-allowed" },
  medGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(280px, 100%), 1fr))",
    gap: 12,
  },
  medCard: {
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 14,
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minWidth: 0,
  },
  medCardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  medName: { fontWeight: 800, fontSize: 15, wordBreak: "break-word" },
  medCat: { fontSize: 12, color: "#7C918F", marginTop: 2 },
  iconBtnMuted: {
    border: "none",
    background: "none",
    color: "#B7C7C5",
    cursor: "pointer",
    padding: 4,
    flexShrink: 0,
  },
  quickRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#F7FAF9",
    border: "1px solid #E4EEEC",
    borderRadius: 10,
    padding: "6px 8px",
  },
  stepBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    border: "none",
    background: "#145C5C",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  quickQtyBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    lineHeight: 1.1,
    flex: 1,
    minWidth: 0,
  },
  noBatch: { fontSize: 12.5, color: "#B7C7C5", fontStyle: "italic" },
  shelfTimeline: { display: "flex", flexDirection: "column", gap: 6 },
  batchChip: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderRight: "3px solid",
    borderRadius: 8,
    padding: "7px 10px",
    fontSize: 12,
    gap: 6,
    flexWrap: "wrap",
  },
  batchDeleteBtn: {
    border: "none",
    background: "none",
    cursor: "pointer",
    color: "inherit",
    opacity: 0.6,
    padding: 2,
    flexShrink: 0,
  },
  medCardActions: { display: "flex", gap: 8, marginTop: 2, flexWrap: "wrap" },
  emptyState: {
    background: "#fff",
    border: "1px dashed #DCE8E6",
    borderRadius: 14,
    padding: "40px 16px",
    textAlign: "center",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(20,30,29,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    zIndex: 50,
  },
  modalBox: {
    background: "#fff",
    borderRadius: 16,
    padding: 16,
    width: "100%",
    maxHeight: "88vh",
    overflowY: "auto",
  },
  modalHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  form: { display: "flex", flexDirection: "column", gap: 12 },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    fontSize: 12.5,
    color: "#3A4E4C",
    fontWeight: 600,
  },
  input: {
    border: "1px solid #DCE8E6",
    borderRadius: 8,
    padding: "9px 10px",
    fontSize: 13.5,
    fontFamily: "inherit",
    color: "#1B2B2A",
    // Explicit, so this never falls back to the browser's native dark-mode
    // form-control background (which, combined with the explicit dark text
    // color above, made fields unreadable — see src/index.css
    // `color-scheme: light` for the other half of that fix).
    background: "#fff",
    width: "100%",
  },
  selectWrap: { position: "relative" },
  select: {
    border: "1px solid #DCE8E6",
    borderRadius: 8,
    padding: "9px 30px 9px 10px",
    fontSize: 13.5,
    fontFamily: "inherit",
    color: "#1B2B2A",
    width: "100%",
    appearance: "none",
    background: "#fff",
  },
  selectChevron: {
    position: "absolute",
    left: 10,
    top: 12,
    color: "#7C918F",
    pointerEvents: "none",
  },
  // Mobile-only category filter (replaces the horizontal category strip —
  // see CategorySidebar.jsx / global.css .category-mobile-select). Hidden
  // by default via CSS; shown only at the mobile breakpoint. Reuses the
  // exact same white-card/border/radius language as the rest of the app.
  categoryMobileSelect: {
    flexDirection: "column",
    gap: 8,
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
    width: "100%",
  },
  categoryMobileActions: { display: "flex", gap: 8, flexWrap: "wrap" },
  historySummaryRow: {
    display: "flex",
    gap: 10,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  historySummaryBox: {
    flex: "1 1 120px",
    background: "#F1F6F5",
    borderRadius: 10,
    padding: "10px 12px",
    textAlign: "center",
  },
  rangeChips: { display: "flex", gap: 6, marginBottom: 12, flexWrap: "wrap" },
  rangeChip: (active) => ({
    border: active ? "1px solid #145C5C" : "1px solid #DCE8E6",
    background: active ? "#E7F3F1" : "#fff",
    color: active ? "#145C5C" : "#5B6E6D",
    borderRadius: 999,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  }),
  logTableWrap: {
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 14,
    overflow: "auto",
    maxWidth: "100%",
  },
  logTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
    minWidth: 420,
  },
  th: {
    textAlign: "right",
    padding: "10px 14px",
    background: "#F1F6F5",
    color: "#5B6E6D",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  td: {
    padding: "10px 14px",
    borderTop: "1px solid #EEF3F2",
    whiteSpace: "nowrap",
  },
  // Grouped "سجل الصرف" overview — one professional data table, one row per
  // medication, with an inline-expandable nested table (not a modal, not a
  // grid of floating cards).
  logGroupRow: {
    cursor: "pointer",
  },
  logGroupNameCell: {
    fontWeight: 800,
    fontSize: 14,
    color: "#1B2B2A",
    wordBreak: "break-word",
    whiteSpace: "normal",
  },
  logExpandBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginInlineStart: "auto",
    border: "none",
    background: "none",
    color: "#145C5C",
    fontWeight: 700,
    fontSize: 12.5,
    fontFamily: "inherit",
    cursor: "pointer",
    padding: "4px 2px",
    whiteSpace: "nowrap",
  },
  logDetailsCell: {
    padding: "10px 14px 16px",
    background: "#F7FAF9",
    borderTop: "1px solid #EEF3F2",
  },
  logDetailsWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  logDetailsTitle: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "#3A4E4C",
  },
  settingsSectionTitle: {
    fontWeight: 800,
    fontSize: 13.5,
    color: "#1B2B2A",
    marginBottom: 10,
  },
  labelEditGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(220px, 100%), 1fr))",
    gap: 10,
  },

  // ---------------------------------------------------------------------
  // Auth screen (visual/UX polish only). Scoped to src/components/auth/* —
  // nothing here is referenced by the dashboard, so this cannot change the
  // dashboard's appearance. Brand colors/font-stack intentionally match the
  // dashboard header (#145C5C / #2E8B8B gradient, same system font stack)
  // for visual continuity, not shared style objects.
  // ---------------------------------------------------------------------
  authPage: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#F3F7F6",
    backgroundImage: "radial-gradient(circle, rgba(20,92,92,0.07) 1px, transparent 1px)",
    backgroundSize: "24px 24px",
    position: "relative",
    overflow: "hidden",
    fontFamily: "'Segoe UI', Tahoma, 'Geeza Pro', Arial, sans-serif",
    color: "#1B2B2A",
  },
  authDecorCircleA: {
    position: "absolute",
    width: "clamp(220px, 38vw, 460px)",
    height: "clamp(220px, 38vw, 460px)",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(20,92,92,0.10), transparent 70%)",
    top: -120,
    insetInlineEnd: -100,
    pointerEvents: "none",
    zIndex: 0,
  },
  authDecorCircleB: {
    position: "absolute",
    width: "clamp(180px, 30vw, 380px)",
    height: "clamp(180px, 30vw, 380px)",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(46,139,139,0.10), transparent 70%)",
    bottom: -140,
    insetInlineStart: -80,
    pointerEvents: "none",
    zIndex: 0,
  },
  authHeader: {
    background: "linear-gradient(135deg, #145C5C 0%, #0E4747 100%)",
    padding: "14px 20px",
    position: "relative",
    zIndex: 1,
  },
  authHeaderInner: {
    maxWidth: 1040,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  authHeaderBadge: {
    width: 34,
    height: 34,
    borderRadius: 9,
    background: "rgba(255,255,255,0.14)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  authHeaderTitle: { fontSize: 15.5, margin: 0, fontWeight: 800, color: "#F6F5F1" },
  authHeaderSubtitle: { fontSize: 11, opacity: 0.82, marginTop: 2, color: "#F6F5F1" },
  authMain: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "36px 16px 48px",
    position: "relative",
    zIndex: 1,
  },
  authCard: {
    width: "min(92%, 540px)",
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 24,
    padding: "36px 32px",
    boxShadow: "0 20px 45px -20px rgba(20,60,58,0.25), 0 2px 8px rgba(20,60,58,0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 22,
  },
  authCardHead: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    textAlign: "center",
  },
  authCardIconBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    background: "linear-gradient(135deg, #145C5C 0%, #2E8B8B 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 18px -6px rgba(20,92,92,0.45)",
  },
  authCardWelcome: { fontSize: 13, color: "#7C918F", fontWeight: 600 },
  authCardBrand: { fontSize: 21, fontWeight: 800, color: "#12201F", marginTop: -4 },
  authCardDescription: { fontSize: 12.5, color: "#5B6E6D", lineHeight: 1.6, maxWidth: 360 },
  authTabTrack: {
    display: "flex",
    gap: 4,
    background: "#F1F6F5",
    borderRadius: 12,
    padding: 4,
  },
  authTab: (active) => ({
    flex: 1,
    border: "none",
    cursor: "pointer",
    padding: "10px 12px",
    borderRadius: 9,
    fontSize: 13,
    fontWeight: 700,
    background: active ? "#145C5C" : "transparent",
    color: active ? "#fff" : "#5B6E6D",
    fontFamily: "inherit",
  }),
  authLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 12.5,
    color: "#3A4E4C",
    fontWeight: 700,
  },
  authInputWrap: { position: "relative" },
  authInputIcon: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    insetInlineEnd: 14,
    color: "#8FA5A3",
    pointerEvents: "none",
  },
  authInput: {
    border: "1px solid #DCE8E6",
    borderRadius: 12,
    padding: "12px 42px 12px 14px",
    fontSize: 14,
    fontFamily: "inherit",
    color: "#1B2B2A",
    width: "100%",
    background: "#FBFDFC",
  },
  authError: {
    color: "#9A2E23",
    background: "#FBE7E4",
    border: "1px solid #F3CFC9",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.6,
  },
  authSuccessNote: {
    fontSize: 13,
    color: "#145C5C",
    background: "#E7F3F1",
    border: "1px solid #CFE4E1",
    borderRadius: 12,
    padding: "16px 14px",
    lineHeight: 1.7,
  },
  authPrimaryBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    background: "#145C5C",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "13px 16px",
    fontSize: 14.5,
    fontWeight: 800,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  authFooter: {
    textAlign: "center",
    fontSize: 11,
    color: "#8FA5A3",
    padding: "0 16px 22px",
    position: "relative",
    zIndex: 1,
  },

  // ---------------------------------------------------------------------
  // Today/Triage view — reuses the app's existing card/spacing/color
  // language (URGENCY_STYLE tones, medCard-like radii) rather than
  // introducing a new visual style.
  // ---------------------------------------------------------------------
  triageIntro: { fontSize: 12.5, color: "#5B6E6D", marginBottom: 14 },
  triageSection: {
    background: "#fff",
    border: "1px solid #DCE8E6",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  triageSectionHead: { display: "flex", alignItems: "center", gap: 8 },
  triageSectionIcon: {
    width: 26,
    height: 26,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  triageSectionTitle: { fontWeight: 800, fontSize: 13.5, color: "#1B2B2A" },
  triageSectionCount: {
    marginInlineStart: "auto",
    fontSize: 11.5,
    fontWeight: 700,
    color: "#7C918F",
    background: "#F1F6F5",
    borderRadius: 999,
    padding: "2px 9px",
  },
  triageEmpty: { fontSize: 12.5, color: "#B7C7C5", padding: "12px 2px 2px" },
  triageList: {
    marginTop: 10,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  triageItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    width: "100%",
    textAlign: "right",
    border: "1px solid #EEF3F2",
    background: "#F7FAF9",
    borderRadius: 10,
    padding: "9px 12px",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  triageItemName: { fontWeight: 700, fontSize: 13, color: "#1B2B2A", minWidth: 0 },
  triageItemMeta: { fontSize: 11.5, color: "#7C918F" },

  // ---------------------------------------------------------------------
  // Profile page (account info / change password / development team).
  // Reuses the same section/label/input language as SettingsPanel and the
  // auth screen rather than introducing new visual patterns.
  // ---------------------------------------------------------------------
  profileSection: { display: "flex", flexDirection: "column", gap: 22 },
  profileInfoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(220px, 100%), 1fr))",
    gap: 10,
  },
  profileInfoRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    background: "#F7FAF9",
    border: "1px solid #E4EEEC",
    borderRadius: 10,
    padding: "10px 12px",
    minWidth: 0,
  },
  profileInfoIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    background: "#E7F3F1",
    color: "#145C5C",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profileInfoLabel: { fontSize: 11.5, color: "#7C918F", fontWeight: 600 },
  profileInfoValue: {
    fontSize: 13,
    color: "#1B2B2A",
    fontWeight: 700,
    marginTop: 2,
    wordBreak: "break-word",
  },
  // Read-only value + pencil button, shown when an editable profile field
  // (full name / job title) is NOT currently being edited.
  profileValueRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 2,
  },
  profileEditPencilBtn: {
    border: "none",
    background: "none",
    color: "#7C918F",
    cursor: "pointer",
    padding: 2,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
  },
  // Shown instead of profileValueRow while that same field is being edited —
  // only ever one field at a time, since each EditableProfileField instance
  // owns its own `editing` state independently.
  profileEditRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  profileEditInput: {
    flex: 1,
    minWidth: 0,
    border: "1px solid #145C5C",
    borderRadius: 8,
    padding: "6px 8px",
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1B2B2A",
    background: "#fff",
  },
  profileEditActions: { display: "flex", gap: 4, flexShrink: 0 },
  profileEditBtnSave: {
    width: 26,
    height: 26,
    borderRadius: 7,
    border: "none",
    background: "#145C5C",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  profileEditBtnCancel: {
    width: 26,
    height: 26,
    borderRadius: 7,
    border: "1px solid #DCE8E6",
    background: "#fff",
    color: "#7C918F",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  profileFieldError: {
    color: "#9A2E23",
    fontSize: 11.5,
    marginTop: 5,
    lineHeight: 1.5,
  },
  profileFieldSuccess: {
    color: "#145C5C",
    fontSize: 11.5,
    fontWeight: 700,
    marginTop: 5,
  },
  // Interactive counterpart of authInputIcon — same position, but a real
  // clickable button (pointer-events enabled) for the password show/hide
  // toggle, instead of a decorative, non-interactive icon.
  authInputToggleBtn: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    insetInlineEnd: 10,
    border: "none",
    background: "none",
    color: "#8FA5A3",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  devGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(260px, 100%), 1fr))",
    gap: 12,
  },
  devCard: {
    background: "#F7FAF9",
    border: "1px solid #E4EEEC",
    borderRadius: 12,
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  devCardHead: { display: "flex", alignItems: "center", gap: 10 },
  devAvatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #145C5C 0%, #2E8B8B 100%)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    fontWeight: 800,
    fontSize: 14,
  },
  devName: { fontWeight: 800, fontSize: 14, color: "#1B2B2A" },
  devDetailRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    fontSize: 12,
    color: "#3A4E4C",
    lineHeight: 1.6,
  },
};
